#For my cluster I need to use this apiVersion
#apiVersion: apps.openliberty.io/v1
apiVersion: openliberty.io/v1beta1
kind: OpenLibertyApplication
metadata:
  name: cos
spec: 
  applicationImage: 'image-registry.openshift-image-registry.svc:5000/dev/cos'
